### ISSUE TITLE
Exec stdin might lost data if pass in `Readable.from(string)`

### ISSUE THREAD

**Issue by hax** [kubernetes-client/javascript#1772] opened 2024-07-03 12:33 UTC
https://github.com/kubernetes-client/javascript/blob/b4fd82f2d20e46ad6a60f9b83c38553f5674a4dc/src/web-socket-handler.ts#L58

Current implementation assume stdin is always a binary stream, but it does not really check the type. So if pass `Readable.from(string)` as stdin, most time it works, unless the string contains non-ASCII characters, in such case, `data` is string and  `data.length` is number of UTF16 code units, which will smaller than the number of UTF8 code units or bytes.

I suggest the implementation should either deal with the string case, or just throw type error if not buffer.

**Comment by brendandburns** [comment] 2024-07-03 16:04
Happy to take a PR with a unit test to repro this and either fix that you prefer.

**Comment by cjihrig** [comment] 2024-09-27 20:35
Here is a small reproduction:

```js
'use strict';
const { deepStrictEqual } = require('node:assert');
const { Readable } = require('node:stream');
const { test } = require('node:test');
const { WebSocketHandler } = require('./dist/web-socket-handler');

test('repro', () => {
  const { promise, resolve } = Promise.withResolvers();
  const stream = new Readable({ read() {} });
  const ws = {
    close() {},
    send(data) {
      deepStrictEqual(data, Buffer.from([0x0f, 0xe2, 0x98, 0x83]));
      resolve();
    }
  };

  stream.setEncoding('utf8');
  stream.push('☃');
  WebSocketHandler.handleStandardInput(ws, stream, 0x0f);
  return promise;
});
```

I'll work on a fix.

**Comment by cjihrig** [comment] 2024-10-01 16:38
I think this can be closed since https://github.com/kubernetes-client/javascript/pull/1900 was merged. I'm a bit surprised that it didn't auto-close.

**Closed** 2024-12-19 15:09 UTC
