### ISSUE TITLE
Compilation breaks on Typescript 4.8.2, Ubuntu 20.04 

### ISSUE THREAD

**Issue by eyalb181** [kubernetes-client/javascript#864] opened 2022-08-28 14:45 UTC
When running tsc, it breaks with the following errors:
```
root@ec42f57e3eda:/mirrord/vscode-ext# tsc
node_modules/@kubernetes/client-node/dist/informer.d.ts:19:41 - error TS2344: Type 'T' does not satisfy the constraint 'KubernetesObject'.

19     on(verb: string, fn: ObjectCallback<T>): void;
                                           ~

  node_modules/@kubernetes/client-node/dist/informer.d.ts:18:27
    18 export interface Informer<T> {
                                 ~
    This type parameter might need an `extends KubernetesObject` constraint.

node_modules/@kubernetes/client-node/dist/informer.d.ts:20:42 - error TS2344: Type 'T' does not satisfy the constraint 'KubernetesObject'.

20     off(verb: string, fn: ObjectCallback<T>): void;
                                            ~

  node_modules/@kubernetes/client-node/dist/informer.d.ts:18:27
    18 export interface Informer<T> {
                                 ~
    This type parameter might need an `extends KubernetesObject` constraint.

node_modules/@kubernetes/client-node/dist/informer.d.ts:24:106 - error TS2344: Type 'T' does not satisfy the constraint 'KubernetesObject'.

24 export declare function makeInformer<T>(kubeconfig: KubeConfig, path: string, listPromiseFn: ListPromise<T>, labelSelector?: string): Informer<T>;
                                                                                                            ~

  node_modules/@kubernetes/client-node/dist/informer.d.ts:24:38
    24 export declare function makeInformer<T>(kubeconfig: KubeConfig, path: string, listPromiseFn: ListPromise<T>, labelSelector?: string): Informer<T>;
                                            ~
    This type parameter might need an `extends KubernetesObject` constraint.


Found 3 errors in the same file, starting at: node_modules/@kubernetes/client-node/dist/informer.d.ts:19 
```

** Client Version **
0.16.3

** Server Version **
N/A

**To Reproduce**
Run tsc on Ubuntu 20.04 with TypeScript 4.8.2

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - NodeJS Version 12.22.9
 
**Additional context**

You can view the error in a wider context in our [CI logs](https://github.com/metalbear-co/mirrord/runs/8057801870?check_suite_focus=true).

**Comment by yotamselementor** [comment] 2022-08-28 20:40
@brendanburns / @brendandburns any chance you release a new version to resolve this issue?

**Comment by brendandburns** [comment] 2022-08-29 15:30
I will try to reproduce, but you appear to be calling `tsc` on `tsc
node_modules/@kubernetes/client-node/dist/informer.d.ts` which is the generated typings for the library.

Is there a reason why you are trying to compile the typings?

**Comment by brendandburns** [comment] 2022-08-29 19:25
Hrm, this library has already been compiled from Typescript, and I don't think that the typings need/should be compiled.

An easier workaround would be to add `"!node_modules/@kubernetes/**"` to your `tsconfig.json` but I'll try to see if we can fix this on our side also, but that file is created by `tsc` I suspect that we need to upgrade our typescript in `package.json`

**Comment by yotamselementor** [comment] 2022-08-29 20:00
> Hrm, this library has already been compiled from Typescript, and I don't think that the typings need/should be compiled.
> 
> An easier workaround would be to add `"!node_modules/@kubernetes/**"` to your `tsconfig.json` but I'll try to see if we can fix this on our side also, but that file is created by `tsc` I suspect that we need to upgrade our typescript in `package.json`

@brendandburns this issue has been fixed in #847 - the `@types/*` modules have all been moved to the `devDependencies` section, so all we need is a new release

**Comment by brendandburns** [comment] 2022-09-02 16:04
@yotamselementor if I can get an lgtm on #867 we can cut a new release.

**Comment by yotamselementor** [comment] 2022-09-02 16:31
> @yotamselementor if I can get an lgtm on #867 we can cut a new release.

Thanks, that's great!

**Comment by brendandburns** [comment] 2022-09-11 15:18
I just pushed `0.17.1` to npm which I believe should fix this, please confirm (and apologies for the delay)

**Comment by yotamselementor** [comment] 2022-09-12 04:45
> I just pushed `0.17.1` to npm which I believe should fix this, please confirm (and apologies for the delay)

@brendandburns - thanks for your trouble!
It works on my project. However, I had to add some devDependencies to make it happen - `@types/js-yaml`, `@types/request` & `@types/ws` - I am not sure as to why.

**Comment by brendandburns** [comment] 2022-09-13 16:37
Closing this issue, since it is fixed. I will look into the `devDependencies` issue separately.

**Comment by eyalb181** [comment] 2022-09-17 16:56
Hey, sorry for the delayed response. Running it on OSX this time with Typescript 4.8.3, getting the same errors (in addition to having to add the libraries @yotamselementor mentioned as devDependencies):
```
node_modules/@kubernetes/client-node/dist/informer.d.ts:26:65 - error TS2344: Type 'T' does not satisfy the constraint 'KubernetesObject'.

26     on(verb: ADD | UPDATE | DELETE | CHANGE, cb: ObjectCallback<T>): void;
                                                                   ~

  node_modules/@kubernetes/client-node/dist/informer.d.ts:25:27
    25 export interface Informer<T> {
                                 ~
    This type parameter might need an `extends KubernetesObject` constraint.

node_modules/@kubernetes/client-node/dist/informer.d.ts:28:66 - error TS2344: Type 'T' does not satisfy the constraint 'KubernetesObject'.

28     off(verb: ADD | UPDATE | DELETE | CHANGE, cb: ObjectCallback<T>): void;
                                                                    ~

  node_modules/@kubernetes/client-node/dist/informer.d.ts:25:27
    25 export interface Informer<T> {
                                 ~
    This type parameter might need an `extends KubernetesObject` constraint.

node_modules/@kubernetes/client-node/dist/informer.d.ts:33:106 - error TS2344: Type 'T' does not satisfy the constraint 'KubernetesObject'.

33 export declare function makeInformer<T>(kubeconfig: KubeConfig, path: string, listPromiseFn: ListPromise<T>, labelSelector?: string): Informer<T> & ObjectCache<T>;
                                                                                                            ~

  node_modules/@kubernetes/client-node/dist/informer.d.ts:33:38
    33 export declare function makeInformer<T>(kubeconfig: KubeConfig, path: string, listPromiseFn: ListPromise<T>, labelSelector?: string): Informer<T> & ObjectCache<T>;
                                            ~
    This type parameter might need an `extends KubernetesObject` constraint.


Found 3 errors in the same file, starting at: node_modules/@kubernetes/client-node/dist/informer.d.ts:26
```

Easily worked around with --skipLibCheck though.

**Comment by JarnoRFB** [comment] 2022-09-22 07:08
Same error for me on Ubuntu 22.04 with Typescript 4.8.3.

**Comment by rbnayax** [comment] 2022-10-17 22:19
same here - seems like this issue should be reopened

**Comment by bencooper222** [comment] 2022-10-18 18:47
Same here with TS 4.6.4

**Comment by brendandburns** [comment] 2022-10-20 20:01
With node `16.18.0` and typescript `4.8.4` this all works for me assuming that you specify `esModuleInterop:true` in your `tsconfig.json` or `--esModuleInterop` on the command line.

Note that if you compile a file directly (`tsc example.ts`) typescript ignores your `tsconfig.json` so if you are doing that you need to use the command line flag.

From my reading of the npm spec:
https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file

`@typings` files are `devDependencies` not main dependencies but I'm happy to be convinced otherwise if people have sources, or canonical examples where this isn't true.

If you are still seeing errors, can you send me a repro (source code + instructions) so that I can test locally?

**Comment by brendandburns** [comment] 2022-10-20 20:01
Another option is to simply add `exclude: [ "node_modules" ]` to your `tsconfig.json`

**Comment by MichalCz** [comment] 2022-10-21 13:03
@brendandburns we have the same issue here: https://github.com/scramjetorg/transform-hub/pull/716

The specific issue can be seen here:

https://github.com/scramjetorg/transform-hub/actions/runs/3297553596/jobs/5438510465#step:6:119

The version is `0.17.1` so it seems this indeed is not solved.

Reproduce:

```sh
git clone git@github.com:scramjetorg/transform-hub.git
yarn
yarn build:packages
```

Of course workarounds work, but it is not great for us, since we'd need to remove lib checking for all libs...

**Comment by MichalCz** [comment] 2022-10-21 13:29
I pushed a downgrade to `typescript=4.7`.

https://github.com/scramjetorg/transform-hub/actions/runs/3297789268/jobs/5439057436

**Comment by JarnoRFB** [comment] 2022-10-21 13:54
I put together a minial example here https://github.com/JarnoRFB/kube-typerror. Let me know if this helps.
The error is there even though `node_modules` is excluded and `esModuleInterop` is turned on. Only `skipLibCheck` helps, but that turns off the checking of all libs, as was already mentioned.

**Comment by brendandburns** [comment] 2022-10-21 15:34
@JarnoRFB thanks for the example, I will try to repro locally.

**Comment by brendandburns** [comment] 2022-10-21 16:01
Ah, the reason it didn't repro for me is that this is specific to using the informer class...  I will look into this.

**Comment by brendandburns** [comment] 2022-10-21 16:11
@JarnoRFB thanks for the repro, I fixed this via:

https://github.com/kubernetes-client/javascript/pull/897

**Closed** 2022-10-28 20:46 UTC

**Comment by ipsi** [comment] 2022-11-29 14:49
When you say 0.17.1, did you mean 0.17.2, given that 0.17.1 was related in September? Or is this slated for inclusion in 0.18.0?

**Comment by JarnoRFB** [comment] 2022-11-29 15:43
@ipsi Somehow the changed got merged, but never released. See the comments in https://github.com/kubernetes-client/javascript/pull/897

**Comment by Timothy-Dement** [comment] 2022-12-08 16:17
Is there an update on when this will be released? The last comment on https://github.com/kubernetes-client/javascript/pull/897 was from 24 days ago

**Comment by brendandburns** [comment] 2022-12-15 23:40
Please try `18.0.0` https://www.npmjs.com/package/@kubernetes/client-node

**Comment by JarnoRFB** [comment] 2022-12-19 13:36
@brendandburns works like a charm :ok_hand:
