### ISSUE TITLE
Informer stops following updates after ~hour

### ISSUE THREAD

**Issue by Michal-lolo** [kubernetes-client/javascript#958] opened 2023-01-05 13:11 UTC
**Describe the bug**
Informer stops following updates after ~hour without any _error_ nor _connect_ event. After informer restart it works fine again, so as workaround I've added interval to restart informer, but this is not graceful solution.

** Client Version **
e.g. `0.17.1`

** Server Version **
e.g. `1.22.15`

**To Reproduce**

1. Follow [example](https://github.com/kubernetes-client/javascript/blob/master/examples/typescript/informer/informer.ts) informer to create new informer.
2. Wait 65 minutes.
3. Create/delete/update pod and check the logs.

**Expected behavior**
Informer should watch pods continuously (reconnect) or at least throw some error in case of interruption/loosing connection with server.

** Example Code**
[example](https://github.com/kubernetes-client/javascript/blob/master/examples/typescript/informer/informer.ts) informer 

**Environment (please complete the following information):**
Docker image (node-12):
 - OS: Debian GNU/Linux 9 (stretch)
 - NodeJS Version: v12.22.12

**Additional context**

**Comment by brendandburns** [comment] 2023-01-05 17:08
@Michal-lolo there's a pretty extensive discussion of this issue here:

https://github.com/kubernetes-client/javascript/issues/596

With related links to various solutions. Upgrading nodejs to 16 seems to be one of the necessary ingredients.

I reopened #596 and I'm going to close this issue as a duplicate of that one.

**Closed by brendandburns** 2023-01-05 17:08 UTC
