### ISSUE TITLE
Get error when start the client

### ISSUE THREAD

**Issue by lchrennew** [kubernetes-client/javascript#878] opened 2022-09-17 16:28 UTC
**Describe the bug**
<img width="754" alt="image" src="https://user-images.githubusercontent.com/1522365/190866692-a76d479e-8d24-49d8-a085-32934871a567.png">

** Client Version **
`0.17.1`

** Server Version **
N/A

**To Reproduce**
```
yarn add @kubernetes/client-node

nvm use 18

node index.js
```

**Expected behavior**
No Error thrown

** Example Code**
--

**Environment (please complete the following information):**
 - OS: MacOSX
 - NodeJS Version 18
 - Cloud runtime --

**Additional context**
#832

**Comment by dominykas** [comment] 2022-09-19 08:51
Duplicate of #876?

**Comment by brendandburns** [comment] 2022-09-19 21:38
Yeah, this is a duplicate of #876, closing.

**Closed by brendandburns** 2022-09-19 21:38 UTC
