### ISSUE TITLE
Self signed certificate in certificate chain.

### ISSUE THREAD

**Issue by HoloPanio** [kubernetes-client/javascript#1451] opened 2023-11-25 18:12 UTC
# Prolouge
Before I get into this, I need to state that I am using this library in [Bun](https://bun.sh), and when I moved some demo code with my kubeconfig, it worked fine.

# The Issue
I was trying some very basic kubernetes methods such as just fetching pods or namespaces, and when I went to run it, I was met with the following error: `Error: SELF_SIGNED_CERT_IN_CHAIN: self signed certificate in certificate chain`.  I have tried for many hours to get this error to go away, but nothing I have done has worked.  I have tried everything, but nothing seems to work.  I tried setting it to ignore tls verification in the kubeconfig file, but no dice.

 I have tried it with the env var "NODE_TLS_REJECT_UNAUTHORIZED=0", which produced a new error that was: 
![image](https://github.com/kubernetes-client/javascript/assets/30759238/71ccb96e-dc6d-4a56-8e86-5efca60b41e2)

I am pretty sure this is a problem with Bun, and if there is a known, or possible fix that I could introduce that would at least circumvent this error long enough for a permeant fix to be introduced, that would be awesome.

## Additional Information

Bun Version: `1.0.8`
k8s Package Version: `^0.20.0`

**Comment by brendandburns** [comment] 2023-11-27 18:45
How are you loading your kubeconfig? Is it from a YAML file? If it is from YAML, adding `insecure-tls-skip-verify` may help (https://kubernetes.io/docs/reference/config-api/kubeconfig.v1/#Cluster)

If it is being loaded from memory, you will need to figure out how to convince Bun to make `cluster.skipTLSVerify` be true.

Hope that helps.

**Comment by HoloPanio** [comment] 2023-11-29 16:38
> How are you loading your kubeconfig? Is it from a YAML file? If it is from YAML, adding `insecure-tls-skip-verify` may help (https://kubernetes.io/docs/reference/config-api/kubeconfig.v1/#Cluster)
> 
> If it is being loaded from memory, you will need to figure out how to convince Bun to make `cluster.skipTLSVerify` be true.
> 
> Hope that helps.

@brendandburns I did this and it did nothing.  That isn't the cert that is erroring at, it is the user certs from everything I have been able to figure out.

**Comment by brendandburns** [comment] 2023-11-29 17:21
Given that I don't think that this is a problem in this client, because using client certificates works correctly in my experience. We're happy to help if you have a clean repro w/o Bun involved, but for now I'm not sure there's much more we can do without a reproducible code snippet.

**Comment by HoloPanio** [comment] 2023-12-03 13:45
It is an issue with Bun HTTP client apparently: https://github.com/oven-sh/bun/issues/7332

**Comment by brendandburns** [comment] 2023-12-11 17:43
Closing since it is apparently not this client.

**Closed by brendandburns** 2023-12-11 17:43 UTC
