### ISSUE TITLE
Calling `close` on exec web socket does not kill corresponding process

### ISSUE THREAD

**Issue by NolanChan** [kubernetes-client/javascript#441] opened 2020-05-01 18:58 UTC
Hi! 

I've currently got some code running as such:

```
const ws = await exec.exec(... , '/bin/bash', ...)
...
ws.close()
// I've also tried ws. terminate()
```

When calling `ws.close()`, the websocket is properly closed but the corresponding `bash` process is not killed on the container. When I use `kubectl exec '/bin/bash'` and exit using `CTRL+D`, the process is properly killed on the container.

Is the expected behavior to not kill the process? It seems that in the [corresponding issue in the Java repo](https://github.com/kubernetes-client/java/issues/685), you implemented a `destroy` command, but that doesn't seem to exist here.

Thanks!

**Comment by brendandburns** [comment] 2020-05-03 04:36
Hrm, I think the issue is that bash doesn't see `stdin` as having closed, but I'm not sure why that doesn't happen if you close the websocket.

This may be differences between the SPDY implementation that Kubectl uses and the WebSockets implementation that we use.

I will try to explore if I have time, if you find anything more please add it to the issue.

**Comment by brendandburns** [comment] 2020-05-03 04:37
fwiw, when you hit `ctrl-d` I think it actually sends the `ctrl-d` to the process in the container. Have you tried writing the `ctrl-d` character into the `stdin` stream?

**Comment by NolanChan** [comment] 2020-05-05 18:41
I just tried using `ctrl-d` into the process and it was killed properly. As an intermediate solution, I'm now sending the `ctrl-d` command into the process when the user closes the shell page.

**Comment by brendandburns** [comment] 2020-05-06 23:42
I think that's actually the right thing to do. I'm going to close this issue since I think sending `ctrl-d` is the right solution. Please use the `/reopen` command if you need further assistance.

**Closed by brendandburns** 2020-05-06 23:42 UTC
