### ISSUE TITLE
Incorrect type for V1HTTPGetAction-> port

### ISSUE THREAD

**Issue by davidsmf** [kubernetes-client/javascript#466] opened 2020-06-19 05:43 UTC
```typescript
    /**
    * Name or number of the port to access on the container. Number must be in the range 1 to 65535. Name must be an IANA_SVC_NAME.
    */
    'port': object;
```
Upstream this is defined as: 
```
        "port": {
          "$ref": "#/definitions/io.k8s.apimachinery.pkg.util.intstr.IntOrString",
          "description": "Name or number of the port to access on the container. Number must be in the range 1 to 65535. Name must be an IANA_SVC_NAME."
        },
```
and in turn `IntOrString` is 

```
    "io.k8s.apimachinery.pkg.util.intstr.IntOrString": {
      "description": "IntOrString is a type that can hold an int32 or a string.  When used in JSON or YAML marshalling and unmarshalling, it produces or consumes the inner type.  This allows you to have, for example, a JSON field that can accept a name or number.",
      "format": "int-or-string",
      "type": "string"
    },
```
Unfortunately it looks like neither a `Number` or a `string` are valid for something of type `object` in Typescript.

Is this the right place to report this?

**Comment by brendandburns** [comment] 2020-06-19 23:01
Yeah, this is a duplicate of #370, there's some weird interaction between the Kubernetes swagger/open api and the code generator. I haven't been able to debug it properly.

Closing since this is a duplicate.

**Closed by brendandburns** 2020-06-19 23:01 UTC
