### ISSUE TITLE
V1HTTPGetAction.Port type is object

### ISSUE THREAD

**Issue by alexmojo** [kubernetes-client/javascript#467] opened 2020-06-24 08:31 UTC
At this moment V1HTTPGetAction.Port type is ```object```:
https://github.com/kubernetes-client/javascript/blob/master/src/gen/model/v1HTTPGetAction.ts#L35
Is this right? Shoudn't is be ```string | number```?

**Comment by brendandburns** [comment] 2020-06-24 13:48
This is a duplicate of #370, closing in favor of that issue.

tl;dr; you're right, there's something weird with the Kubernetes OpenAPI spec, IntOrStrings and the generator, haven't been able to figure out the problem.

**Closed by brendandburns** 2020-06-24 13:48 UTC
