### ISSUE TITLE
Prevent watch from exiting

### ISSUE THREAD

**Issue by flyboarder** [kubernetes-client/javascript#46] opened 2018-04-29 00:02 UTC
Currently the watch function will exit if the stream is empty, we should have a flag for continuous monitoring. Or is there a better way to be watching for resources?

**Comment by flyboarder** [comment] 2018-05-17 17:30
I fixed this by invoking the watcher again as the callback for a "finished" watcher, this works however I am concerned about the size of the call stack after running for a few days.

**Comment by flyboarder** [comment] 2018-09-18 19:28
@pfremm here you go, it's written in clojurescript
https://github.com/degree9/enterprise/blob/master/src/degree9/kubernetes.cljs#L56-L68

**Comment by brendandburns** [comment] 2018-11-15 23:59
Closing this issue as I think this is "by design" please re-open if you think there is more we can do here...

**Closed by brendandburns** 2018-11-15 23:59 UTC
