### ISSUE TITLE
How to replicate "kubectl cp" in kubernetes client

### ISSUE THREAD

**Issue by ShreyGargLTI** [kubernetes-client/javascript#427] opened 2020-04-07 10:45 UTC
I am trying to copy some files from a pod to local machine.
I am able to do so by " kubectl cp" command but unable to identify how to achieve the same via kubernetes client.

**Comment by brendandburns** [comment] 2020-04-07 16:20
`kubectl cp` isn't an API call. It is a `exec` of `tar -xvzf <foo>`

So if you use the exec per the example here:
https://github.com/kubernetes-client/javascript/blob/master/examples/typescript/exec/exec-example.ts

You can implement the copy behavior.

If you get a good solution, we'd happily take a PR so others can re-use that code.

**Comment by drubin** [comment] 2020-04-07 16:27
Also, this is a duplicate of https://github.com/kubernetes-client/javascript/issues/124 

Maybe we can reopen that and add a frozen lifecycle to it?

**Comment by brendandburns** [comment] 2020-04-07 19:50
Closing this in favor of #124

**Closed by brendandburns** 2020-04-07 19:50 UTC
