### ISSUE TITLE
Ingress servicePort as object?

### ISSUE THREAD

**Issue by mateothegreat** [kubernetes-client/javascript#413] opened 2020-02-14 02:12 UTC
Per https://github.com/kubernetes-client/javascript/blob/master/src/gen/model/networkingV1beta1IngressBackend.ts#L38 the backend's `servicePort` is set as `object` .. shouldn't this be a number or string or am I missing something?

Passing in an arbitrary object returns from the api:

v1beta1.IngressBackend.ServicePort: unmarshalerDecoder: json: cannot unmarshal object into Go value of type int32,

**Comment by brendandburns** [comment] 2020-02-14 04:06
This is a duplicate of #370 

There's some weirdness in how the swagger is converted to typescript where object is being substituted for number.

If you pass a string or a number it should work correctly.

I need to dig into the code gen and/or the openapi spec to figure out what's going wrong, but I haven't had the cycles.

I'm closing this in favor of #370 since it's the same issue. Please use `/reopen` if you want to reopen this issue for any reason.

(and if you have cycles to dig into why this is happening PRs or investigations are very welcome)

**Closed by brendandburns** 2020-02-14 04:06 UTC
