### ISSUE TITLE
Follow Pod Logs for Pending or PodInitializing status

### ISSUE THREAD

**Issue by abdennour** [kubernetes-client/javascript#993] opened 2023-02-18 05:08 UTC
**Describe the bug**
The example [follow-logs.js](https://github.com/kubernetes-client/javascript/blob/0.18.0/examples/follow-logs.js) works only if the pod is **RUNNING**. However, it's does not wait for a **PENDING** pod until being running.

** Client Version **
e.g. `0.18.0`

** Server Version **
e.g. `1.24.1`

**To Reproduce**
1. Having a Pending Pod 
2. Run: https://github.com/kubernetes-client/javascript/blob/0.18.0/examples/follow-logs.js

Getting this error

```log
    kind: 'Status',
    message: 'container "c1" in pod "xxxx" is waiting to start: PodInitializing',
    metadata: V1ListMeta {
      _continue: undefined,
      remainingItemCount: undefined,
      resourceVersion: undefined,
      selfLink: undefined
    },
    reason: 'BadRequest',
    status: 'Failure'
  },
```
 
**Expected behavior**
I expect to wait until the Pod being running, or until the timeout reached

** Example Code**
[Code snippet for what you are doing](https://github.com/kubernetes-client/javascript/blob/0.18.0/examples/follow-logs.js)

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Linux] MacOS
 - NodeJS Version [eg. 10]  16
 - Cloud runtime [e.g. Azure Functions, Lambda] Kubernetes Jobs

**Additional context**
N/A

**Comment by brendandburns** [comment] 2023-02-23 17:55
That's true. The examples are simple by design so that they are easy to understand.

We'd be happy to take a PR to update this example as long as it doesn't get too complicated.

I'm going to close this issue since this is an example.

**Closed by brendandburns** 2023-02-23 17:55 UTC
