### ISSUE TITLE
v1PodDisruptionBudgetSpec.maxUnavailable should be Integer or String

### ISSUE THREAD

**Issue by alex-bezek** [kubernetes-client/javascript#738] opened 2021-11-17 22:32 UTC
In the Pod Disruption Budget Spec, the maxUnavailable and minAvailable attributes are set as objects. The documented yaml format is this
```
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: zk-pdb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: zookeeper
```

The k8s API docs show it should be `IntOrString` https://kubernetes.io/docs/reference/kubernetes-api/policy-resources/pod-disruption-budget-v1/#PodDisruptionBudgetSpec

Other libraries do set it to an IntOrString as well
* https://github.com/fabric8io/kubernetes-client/blob/00a28cc9d69a552589b8aa268e0db4fb5e9186cf/kubernetes-model-generator/kubernetes-model-policy/src/main/resources/schema/validation-schema.json#L999
* https://github.com/kubernetes/client-go/blob/master/applyconfigurations/policy/v1/poddisruptionbudgetspec.go#L29

Is this intentional or a quirk of javascript? Or are these attributes typed incorrectly?

**Comment by brendandburns** [comment] 2021-11-18 18:11
This is duplicate of #675 which itself is a duplicate of #666 

The tl;dr; is that we don't handle IntOrString very well.

There is a discussion [here](https://github.com/kubernetes-client/javascript/issues/666#issuecomment-854785967) of what is needed to do a better job here, but no one has stepped up to do it yet.

If you're willing to take it on, it would be much appreciated!

**Closed by brendandburns** 2021-11-18 18:11 UTC
