### ISSUE TITLE
ObjectSerializer.serialize has bug when Array has odd function on it's prototype

### ISSUE THREAD

**Issue by endlesstravel** [kubernetes-client/javascript#643] opened 2021-04-21 10:28 UTC
**Describe the bug**
when i call api whit normal 
![image](https://user-images.githubusercontent.com/10757838/115530528-711ecb80-a2c6-11eb-867a-b538fbc72559.png)

```
const k8sApi = kc.makeApiClient(k8s.AppsV1Api);
const res = await k8sApi.createNamespacedDeployment(MockNamepase, body);
```
it raise error with output:
![image](https://user-images.githubusercontent.com/10757838/115530274-3321a780-a2c6-11eb-8ad6-8ed64024d1a0.png)

it becuase  project have odd function on Array.prototype
```
Array.prototype.someFunction = function() { .... } 
Array.prototype.someFunction2 = function() { .... } 
```
may be need a warning when has odd function on prototype link of Array ?

** Client Version **
e.g. `0.12.0`

** Server Version **
e.g. `1.19.1`

**Environment (please complete the following information):**
 - OS: centos 8
 - NodeJS 12

**Comment by dominykas** [comment] 2021-04-21 15:19
Is this a duplicate of #642?

But also very curious as to why do you have stuff on Array prototype?

**Comment by brendandburns** [comment] 2021-04-21 17:53
This is a duplicate of #642, but this issue has more detail, so I will close #642 and leave this open.

I don't think we want to do anything here, I don't think adding random functions to base types like Array is a use case that we want to support.

**Comment by endlesstravel** [comment] 2021-04-23 12:46
@dominykas 
these code from an old project where the current project must rely on.
The most time-consuming thing is actually to find out such mistakes.
so, i fix it by make those function can't be enumerable which is quick code :
```javascript
function patchArrayPue() {
  const listx = [];
  for (let k in []) {
    listx.push(k);
  }
  for (let funcName of listx) {
    Object.defineProperty(Array.prototype, funcName, {
      value: Array.prototype[funcName],
      enumerable: false,
      writable: true,
      configurable: true,
    });
  }
}
```
It has to be said that this is one of the challenges of maintaining old projects 😂

**Comment by endlesstravel** [comment] 2021-04-23 12:53
@brendandburns 
Nothing can be perfect 👍  , I understand your approach.

**Comment by brendandburns** [comment] 2021-05-19 14:37
Closing this issue as I believe we're not going to take further action.

Please use /reopen if you need further assistance.

**Closed by brendandburns** 2021-05-19 14:37 UTC
