### ISSUE TITLE
Node patch fails with error code 415

### ISSUE THREAD

**Issue by amit-o** [kubernetes-client/javascript#140] opened 2018-10-28 17:25 UTC
I'm trying to patch a node as unscheduable with the client, but the request fails with 415.

```javascript
const kc = new k8s.KubeConfig();
kc.loadFromDefault();
const k8sApi = kc.makeApiClient(k8s.Core_v1Api);
k8sApi.patchNode('gke-test-default-pool-02c2575a-l0ln', { spec: { unschedulable: true } });
```

Unless I'm doing something wrong, I'm assuming the library doesn't send Content-Type: application/merge-patch+json in the header, as seen [here](https://github.com/kubernetes/kubernetes/issues/61103)

**Comment by brendandburns** [comment] 2018-10-30 04:44
Duplicate of https://github.com/kubernetes-client/javascript/issues/19

**Closed by brendandburns** 2018-10-30 04:44 UTC
