### ISSUE TITLE
Sending commands to pod 

### ISSUE THREAD

**Issue by garrit-schroeder** [kubernetes-client/javascript#561] opened 2020-12-01 00:45 UTC
I would like to setup a database using the javascript client.

but i can not even get creating a test file to work. How can i proceed?

I need to exceute the following commands:

`mysql -u user -p password`

`CREATE DATABASE <database-name>;`

`CREATE USER '<user-name>'@'%' IDENTIFIED BY '<user-password>';`

`GRANT ALL ON <database-name>.* TO '<user-name>'@'%';`

`FLUSH PRIVILEGES;`

       let commands = [
            '/bin/bash',
        ]
        let exec = new k8s.Exec(kc);
        var myws = new Stream.Readable({
            write: function(chunk, encoding, next) {
                console.log(chunk.toString());
                next();
            },
            read(size) {

            }
        });
        let shell = await exec.exec('mysql', 'mysql-master-0', 'mysql', commands, process.stdout, process.stderr, myws, true)
        myws.push('touch /opt/test.txt');
        console.log(shell)
        shell.close();

**Comment by brendandburns** [comment] 2020-12-02 01:08
I think the problem is that you are `await`-ing the result of the exec and then trying to write into the shell after the execution is done.

If you remove the `await` I think it will work correctly.  Although you will also need to send a newline (`\n`) to get the shell to actually pick up the command since bash will wait for the user to hit `enter`

**Comment by garrit-schroeder** [comment] 2020-12-03 16:54
Thanks. I got it working.

For anyone wondering. This works for me:

        let exec = new k8s.Exec(kc);
        var myws = new Stream.Readable({
            read(size) {
            }
        });
        exec.exec('mysql', 'mysql-master-0', 'mysql', '/bin/bash', process.stdout, process.stderr, myws, true)
        myws.push('touch /opt/test.txt\n');

**Comment by brendandburns** [comment] 2020-12-03 17:44
Closing since the problem is resolved.

**Closed by brendandburns** 2020-12-03 17:44 UTC
