### ISSUE TITLE
cpToPod passes an async function into exec's statusCallback, but the promise is never awaited

### ISSUE THREAD

**Issue by Moggers** [kubernetes-client/javascript#1767] opened 2024-07-02 01:52 UTC
cpToPod [passes an async function as the statusCallback](https://github.com/kubernetes-client/javascript/blob/master/src/cp.ts#L90-L93); but [exec does not await the function](https://github.com/kubernetes-client/javascript/blob/master/src/exec.ts#L56-L58)
Once upon a time [it was declared as an asynchronous function](https://github.com/kubernetes-client/javascript/commit/25197421fc7752c510af292e1367d0351274af48#diff-748946b70991cc31404a6e031013af45671e6b08472b4be2c875b0a1a3d92d23L36) but even in that case, the [function wasn't awaited](https://github.com/kubernetes-client/javascript/commit/25197421fc7752c510af292e1367d0351274af48#diff-748946b70991cc31404a6e031013af45671e6b08472b4be2c875b0a1a3d92d23R61).
This appears to result in the throw within cptopod (in cases where stderr is populated or the websocket connection fails) coercing into a promise which never gets handled; resulting ultimately in an uncaught promise rejection.

**Comment by brendandburns** [comment] 2024-07-02 16:04
We'd be happy to take a PR with a test demonstrating the problem, along with the fix.

As it stands right now, I'm not sure this is that easy to reproduce without a unit test (and I'm not certain that this is actually what is causing your problem)

**Comment by xelinorg** [comment] 2024-07-21 11:18
By just reading the code I cam see that **_public async cpToPod_**  on https://github.com/kubernetes-client/javascript/blob/60b5427b4dfe2a26a206af95e54ea65a354162d7/src/cp.ts#L68C4-L68C25 should return a  Promise<void> but does not return anything.

You can not return _**this.execInstance.exec**_ on https://github.com/kubernetes-client/javascript/blob/60b5427b4dfe2a26a206af95e54ea65a354162d7/src/cp.ts#L81 because this returns a Promise<WebSocket.WebSocket>.

You could await at _**this.execInstance.exec**_  to get the websocket and then after examining the status of the websocket conditionally return Promise.resolve() or Promise.reject(). Or if there is not need to examine anything just return Promise.resolve().

I hope this makes sense.

**Comment by cjihrig** [comment] 2024-09-27 15:30
Should this issue be closed since https://github.com/kubernetes-client/javascript/pull/1880 was merged?

**Comment by mstruebing** [comment] 2024-09-28 16:31
Actually yes, thank you.
The keyword in the pull request was wrong so it did not automatically close.

**Closed by mstruebing** 2024-09-28 16:31 UTC
