### ISSUE TITLE
External credential provider for authentication

### ISSUE THREAD

**Issue by weibeld** [kubernetes-client/javascript#151] opened 2018-11-13 23:45 UTC
Does this client support external credential providers as described [here](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins)? This feature was introduced in Kubernetes v1.10 and implemented in the [Go client](https://github.com/kubernetes/enhancements/issues/541), and the [Python client](https://github.com/kubernetes-client/python/issues/514) seems to implement it now too.

The feature allows the client to execute an external command to get a credential token that is then used for authenticating to the API server.

The thing is that this is required for Amazon EKS clusters. The external command here is [aws-iam-authenticator](https://github.com/kubernetes-sigs/aws-iam-authenticator). The authentication has to be configured in the `kubeconfig` file as follows:

~~~yaml
users:
- name: ...test-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - token
        - -i
        - test-cluster
~~~

It seems that if this feature is not implemented, then this client cannot be used for Amazon EKS clusters.

**Comment by brendandburns** [comment] 2018-11-13 23:50
@weibeld it does not currently support 'exec' style authenticators. I'd welcome a PR if you want to add it.

You can see the authenticator specialization here:

https://github.com/kubernetes-client/javascript/blob/master/src/config.ts#L305

It probably needs some re-factoring to support multiple different providers anyway...

**Comment by brendandburns** [comment] 2018-12-04 16:21
Just noticed, this is a duplicate of #34, closing in favor of that issue

**Closed by brendandburns** 2018-12-04 16:21 UTC
