### ISSUE TITLE
Patch doesn't send correct content type header

### ISSUE THREAD

**Issue by woodcockjosh** [kubernetes-client/javascript#344] opened 2019-09-22 21:37 UTC
I am having same problem described here: https://github.com/kubernetes-client/javascript/issues/287

**Comment by brendandburns** [comment] 2019-09-23 16:12
Closing as a duplicate of #287.

I added additional thoughts there about why I don't think it is really a bug. I'm open to ideas about how to improve the code or make it more clear if people have better ideas.

Thanks

**Closed by brendandburns** 2019-09-23 16:12 UTC
