### ISSUE TITLE
Port Forwarding to Services

### ISSUE THREAD

**Issue by mtiller** [kubernetes-client/javascript#453] opened 2020-05-21 19:27 UTC
In `kubectl`, it is possible to specify port forwarding to a Deployment or a Service, not just to a Pod.  This isn't just extremely useful, but it really should be the norm given the reasons for Deployment and Service resources existing in the first place.

As far as I can tell, the `PortForward` implementation in `@kubernetes/client-node` is exclusively for Pods.  Is there a particular reason for this?

Thanks.

**Comment by brendandburns** [comment] 2020-05-22 15:46
This is a duplicate of https://github.com/kubernetes-client/javascript/issues/435

Please see the discussion there. The tl;dr; is that port-forwarding to a service is semantic sugar in kubectl that really just port-forwards to a single pod that implements that service.

We're open to someone adding similar code to this client library if they want to send a PR.

**Comment by brendandburns** [comment] 2020-05-29 18:28
Closing this issue since it's a duplicate.

**Closed by brendandburns** 2020-05-29 18:28 UTC
