### ISSUE TITLE
Enforcing order of execution of command lines when using exec

### ISSUE THREAD

**Issue by fdalm** [kubernetes-client/javascript#213] opened 2019-02-16 15:13 UTC
I'm trying to use exec to pass down a list of commands to a container in order to have a simple CI pipeline in place. I can send and execute all commands (and get logs and exit status) however I'm not being able to enforce the order of execution.

I have tried numerous approaches, some guaranteed to provide a sequential, ordered flow but none has worked so far. Surely, any shortcomings I might have in my Javascript-fu may be showing off... 😕 

Can you guys point me to the right direction?

Here's how I'm using it:

```javascript
 function execute(ns, pod, container, nextTask) {
    const exec = new k8s.Exec(kc);
    return exec.exec(
      ns,
      pod,
      container,
      nextTask,
      process.stdout,
      process.stderr,
      process.stdin,
      true /* tty */,
      (status) => {
        console.log('Exited with status:');
        console.log(JSON.stringify(status, null, 2));
      },
    ).then(result => console.log(result))
    .catch(err => console.error(err));
  }
```

Invoked here:

```javascript
  async function runTasks() {
    for (const task of tasks) {
      let nextTask = task.split(' ');
      await execute(ns.metadata.name, pod.metadata.name, c.name, nextTask);
    }
  }
```

The tasks being executed:
```javascript
  const tasks = [
    'echo Warming up...',
    'git clone https://my-repository-url.org/demo',
    '/bin/sh -c cd demo',
    '/bin/sh -c pwd',
  ]
```
Now, when I get the $PWD, instead of _/demo_, I get _/_, meaning pwd was executed before cd...
I'd highly appreciate any hint, I'm going nuts with this... 😄

**Comment by drubin** [comment] 2019-02-16 18:21
HI @fdalm 

I think this issue has more to do with the way the kubernetes API server handles commands each command is executed in a clean context. Similar to starting a new bash shell. 

But in your case is there a reason why you aren't doing 

```js
const tasks = [
    `/bin/sh -c "echo Warming up... && git clone https://my-repository-url.org/demo &&  cd demo && pwd"`,
  ]
```

It feels logically this would make more sense since its a single script/workflow. 

Each one of these tasks would be similar to doing the following with kubectl. So take a try for your self chances are you want to execute a single script.

`kubectl exec -it $pod echo Warming up...`
`kubectl exec -it $pod git clone https://my-repository-url.org/demo`
`...`

Let me know if this makes sense?

**Comment by brendandburns** [comment] 2019-02-19 10:14
To add a little more to what @drubin is saying:

Each `exec` call happens in it's own shell/context. So your `cd` in one exec doesn't change the working directory for the next `exec`

I'm closing this, since it's not a bug.

**Closed by brendandburns** 2019-02-19 10:14 UTC

**Comment by fdalm** [comment] 2019-02-20 22:42
Hey, @drubin !

Thank you so much for your prompt reply. I missed the notification, sorry!
Upon further research, I reached the conclusion now pinpointed by @brendandburns. The context of the call went under the radar for me.

As for expressing the tasks that way, I was experimenting with a way of describing CI/CD pipelines. It was harder for me to get each command's output for some reason. I guess I'll need to refactor the solution.

Thanks for your helpful hints, extended to @brendandburns 👍
