### ISSUE TITLE
Avoid synchronous exec and file reads

### ISSUE THREAD

**Issue by edvald** [kubernetes-client/javascript#137] opened 2018-10-25 09:59 UTC
This came up in relation to #132. There are several instances of synchronous file reads and one shell exec in the code, that should generally be avoided in Node.js. In order to fix that, we'd need to make several methods async.

The public methods that would need to be made async are:
- `KubeConfig.apiFromDefault()`
- `KubeConfig.apiFromFile()`
- `KubeConfig.applyHTTPSOptions()`
- `KubeConfig.applytoHTTPSOptions()`
- `KubeConfig.applyToRequest()`
- `KubeConfig.loadFromCluster()`
- `KubeConfig.loadFromDefault()`
- `KubeConfig.loadFromFile()`
- `Watch.watch()`
- `WebSocketHandler.connect()`

These are public methods, but I'm not sure if all of them are considered to be user-facing APIs?

Of course we want to avoid having to change APIs, but on the other hand we might get cornered into that anyway if one of these methods needs to at some point do something over the network. So I'd suggest it's worth considering doing it sooner than later - but I'll leave it to the maintainers to decide :) 

I can post a PR for any changes decided, since I've already dug into this.

**Comment by brendandburns** [comment] 2018-10-30 04:41
I think it's ok to migrate these to be async, especially across a minor version boundary (e.g. rev to `0.8.0`)

**Comment by itowlson** [comment] 2018-10-30 07:09
One approach used in some packages is to offer both sync and async versions of such functions. But I guess that dates from when async involved messy Node-style callbacks rather than just using await - nowadays async has no ease of use disadvantage. Agree that if we are going to switch these to async then we should do it sooner rather than later.

**Comment by edvald** [comment] 2018-10-30 15:19
Ok, I can get a PR going for that.

Since we're modifying APIs I have a suggestion to make. The pattern of using the `load*()` and `apply*()` methods to mutate the config and request objects is rather unusual.

A more idiomatic style for the load methods would be static methods that generate a class with the appropriate options (e.g. `kc = KubeConfig.fromString(...)`), and in this case the `loadFromOptions` would basically be the class constructor.

The `apply*()` methods could be better formulated as `get*()` methods, that basically work the same way as the apply methods but actually return the new value instead of mutating the objects.

By outright changing the method names, we'd also avoid a potential source of frustration by immediately surfacing name errors instead of potentially having users run into race conditions after upgrading the library and not being aware that they need to wait for Promises. 

What do you think?

**Comment by itowlson** [comment] 2018-10-30 17:17
@edvald I like this.  Changing names also helps alleviate my concern about subtle breaking changes - with your proposal at least code will fail with a clear explanation at the line where the problem is, rather than with something being unexpectedly undefined ten lines later!

**Comment by brendandburns** [comment] 2018-10-31 00:18
yep, changing names seems good to me too.

Let's make sure we also add something about how to migrate in `README.md`

Thanks

**Comment by edvald** [comment] 2018-10-31 16:08
Alrighty, will do. Just came across a slight stumbling block, which is that the generated API classes expect `applyToRequest` to be synchronous. It's still solvable, but I'll need to get back to this next week.

**Comment by brendandburns** [comment] 2018-11-14 00:05
ah, right... You're going to need to potentially update the swagger generator here:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/typescript-node/api.mustache#L217

and 

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/typescript-node/api.mustache#L435

**Comment by jsimmonsc** [comment] 2019-03-17 23:30
I started digging into supporting oidc token refresh and ran into this issue.  +1 for this. 

I'm not super strong in js and have just started trying to get our company to sign a CLA, so I'm a little limited in my ability to do much...  But is there something I can do to help get this done / merged.

**Closed** 2019-08-15 02:47 UTC
Labels: lifecycle/rotten

**Comment by gabegorelick** [comment] 2020-12-19 22:05
This is still an issue. `KubeConfig` in particular has a bunch of places where it does sync I/O without it being documented.
