### ISSUE TITLE
0.9.1 does not have a dist directory

### ISSUE THREAD

**Issue by ssube** [kubernetes-client/javascript#261] opened 2019-06-01 19:20 UTC
Upgrading to the recent 0.9.1 release causes `TS2307: Cannot find module '@kubernetes/client-node'. ` errors, apparently due to a lack of `dist/index.js` in the package ([as mentioned in this comment](https://github.com/kubernetes-client/javascript/issues/258#issuecomment-497903727)):

```
ls node_modules/@kubernetes/client-node/
total 36K                                                                      
drwxr-xr-x 3 ssube ssube 4.0K Jun  1 14:10 .                                                                       
drwxr-xr-x 3 ssube ssube 4.0K Jun  1 14:10 ..                                                                              
-rwxr-xr-x 1 ssube ssube  142 Jun  1 14:07 CHANGELOG.md                                                        
-rwxr-xr-x 1 ssube ssube  12K Jun  1 14:07 LICENSE                                                                    
drwxr-xr-x 9 ssube ssube 4.0K Jun  1 14:10 node_modules                                                  
-rw-r--r-- 1 ssube ssube 2.5K Jun  1 14:07 package.json                    
-rwxr-xr-x 1 ssube ssube 3.6K Jun  1 14:07 README.md   
```
and
```
tar -xvf client-node-0.9.1.tgz 
package/package.json
package/CHANGELOG.md
package/LICENSE
package/README.md
```

**Comment by brendandburns** [comment] 2019-06-03 15:31
hrmph! there's clearly something broken in our release-generation process. I will try to figure out what the issue is...

**Comment by brendandburns** [comment] 2019-06-03 17:53
I just pushed `0.9.2` which should have fixed this....

Thanks! (and apologies)

**Comment by brendandburns** [comment] 2019-06-04 12:01
Closing since I validated this is working.

**Closed by brendandburns** 2019-06-04 12:01 UTC
